export default function PrivacyPage() {
  const lastUpdated = 'May 5, 2026'

  return (
    <>
      <section className="py-20 md:py-28 bg-ivory">
        <div className="section-container">
          <h1 className="heading-large mb-4">Privacy Policy</h1>
          <p className="subtitle max-w-2xl">
            Your privacy is important to us. Learn how we collect, use, and protect your information.
          </p>
          <p className="text-taupe text-sm mt-6">Last updated: {lastUpdated}</p>
        </div>
      </section>

      <section className="py-20 md:py-28 bg-cream">
        <div className="section-container max-w-3xl">
          {/* Table of Contents */}
          <div className="bg-ivory p-8 rounded-sm border border-warm-stone mb-12">
            <h2 className="heading-xs mb-6">Table of Contents</h2>
            <ul className="space-y-2 text-taupe font-body">
              <li><a href="#interpretation" className="hover:text-gold transition">Interpretation and Definitions</a></li>
              <li><a href="#collecting" className="hover:text-gold transition">Collecting and Using Your Personal Data</a></li>
              <li><a href="#use" className="hover:text-gold transition">Use of Your Personal Data</a></li>
              <li><a href="#retention" className="hover:text-gold transition">Retention of Your Personal Data</a></li>
              <li><a href="#transfer" className="hover:text-gold transition">Transfer of Your Personal Data</a></li>
              <li><a href="#delete" className="hover:text-gold transition">Delete Your Personal Data</a></li>
              <li><a href="#disclosure" className="hover:text-gold transition">Disclosure of Your Personal Data</a></li>
              <li><a href="#children" className="hover:text-gold transition">Children's Privacy</a></li>
              <li><a href="#links" className="hover:text-gold transition">Links to Other Websites</a></li>
              <li><a href="#changes" className="hover:text-gold transition">Changes to This Privacy Policy</a></li>
              <li><a href="#contact" className="hover:text-gold transition">Contact Us</a></li>
            </ul>
          </div>

          <div className="space-y-12">
            {/* Introduction */}
            <div>
              <p className="text-taupe leading-relaxed mb-4 font-body">
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
              </p>
              <p className="text-taupe leading-relaxed font-body">
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
              </p>
            </div>

            {/* Interpretation and Definitions */}
            <div id="interpretation">
              <h2 className="heading-small mb-6">Interpretation and Definitions</h2>
              <h3 className="font-bold text-charcoal mb-4">Interpretation</h3>
              <p className="text-taupe leading-relaxed mb-6 font-body">
                The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
              </p>

              <h3 className="font-bold text-charcoal mb-4">Definitions</h3>
              <div className="space-y-3">
                {[
                  { term: 'Account', def: 'A unique account created for You to access our Service or parts of our Service.' },
                  { term: 'Company', def: 'Refers to Pink & Ochre.' },
                  { term: 'Cookies', def: 'Small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.' },
                  { term: 'Device', def: 'Any device that can access the Service such as a computer, a cellphone or a digital tablet.' },
                  { term: 'Personal Data', def: 'Any information that relates to an identified or identifiable individual.' },
                  { term: 'Service', def: 'Refers to the Website.' },
                  { term: 'Usage Data', def: 'Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).' },
                  { term: 'Website', def: 'Pink & Ochre, accessible from our domain.' },
                  { term: 'You', def: 'The individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.' },
                ].map((item, idx) => (
                  <div key={idx} className="border-l-4 border-gold pl-4">
                    <p className="font-semibold text-charcoal mb-1">{item.term}</p>
                    <p className="text-taupe text-sm font-body">{item.def}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Collecting Data */}
            <div id="collecting">
              <h2 className="heading-small mb-6">Collecting and Using Your Personal Data</h2>

              <h3 className="font-bold text-charcoal mb-4">Types of Data Collected</h3>
              <p className="text-taupe leading-relaxed mb-4 font-body">
                <strong>Personal Data</strong>
              </p>
              <p className="text-taupe leading-relaxed mb-4 font-body">
                While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
              </p>
              <ul className="list-disc list-inside space-y-2 text-taupe font-body ml-4 mb-6">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Usage Data</li>
              </ul>

              <p className="text-taupe leading-relaxed mb-4 font-body">
                <strong>Usage Data</strong>
              </p>
              <p className="text-taupe leading-relaxed mb-4 font-body">
                Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
              </p>

              <h3 className="font-bold text-charcoal mb-4 mt-6">Tracking Technologies and Cookies</h3>
              <p className="text-taupe leading-relaxed mb-4 font-body">
                We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. The technologies We use may include:
              </p>
              <ul className="list-disc list-inside space-y-2 text-taupe font-body ml-4 mb-6">
                <li><strong>Cookies:</strong> A cookie is a small file placed on Your Device. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                <li><strong>Web Beacons:</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons that permit the Company to count users who have visited those pages or opened an email.</li>
              </ul>
            </div>

            {/* Use of Personal Data */}
            <div id="use">
              <h2 className="heading-small mb-6">Use of Your Personal Data</h2>
              <p className="text-taupe leading-relaxed mb-4 font-body">
                The Company may use Personal Data for the following purposes:
              </p>
              <ul className="list-disc list-inside space-y-3 text-taupe font-body ml-4 mb-6">
                <li>To provide and maintain our Service: including to monitor the usage of our Service.</li>
                <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
                <li>For the performance of a contract: the development, compliance and undertaking of any contract with Us through the Service.</li>
                <li>To contact You: By email, telephone calls, SMS, or other equivalent forms of electronic communication regarding updates or informative communications.</li>
                <li>To provide You with news, special offers and general information about other goods, services and events which we offer.</li>
                <li>To manage Your requests: To attend and manage Your requests to Us.</li>
                <li>For other purposes: Data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service.</li>
              </ul>
            </div>

            {/* Retention */}
            <div id="retention">
              <h2 className="heading-small mb-6">Retention of Your Personal Data</h2>
              <p className="text-taupe leading-relaxed mb-4 font-body">
                The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
              </p>
              <p className="text-taupe leading-relaxed font-body">
                Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service.
              </p>
            </div>

            {/* Transfer */}
            <div id="transfer">
              <h2 className="heading-small mb-6">Transfer of Your Personal Data</h2>
              <p className="text-taupe leading-relaxed mb-4 font-body">
                Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
              </p>
              <p className="text-taupe leading-relaxed font-body">
                The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
              </p>
            </div>

            {/* Delete Data */}
            <div id="delete">
              <h2 className="heading-small mb-6">Delete Your Personal Data</h2>
              <p className="text-taupe leading-relaxed mb-4 font-body">
                You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
              </p>
              <p className="text-taupe leading-relaxed mb-4 font-body">
                Our Service may give You the ability to delete certain information about You from within the Service. You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information.
              </p>
              <p className="text-taupe leading-relaxed font-body">
                Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
              </p>
            </div>

            {/* Disclosure */}
            <div id="disclosure">
              <h2 className="heading-small mb-6">Disclosure of Your Personal Data</h2>

              <h3 className="font-bold text-charcoal mb-4">Business Transactions</h3>
              <p className="text-taupe leading-relaxed mb-6 font-body">
                If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
              </p>

              <h3 className="font-bold text-charcoal mb-4">Law Enforcement</h3>
              <p className="text-taupe leading-relaxed mb-6 font-body">
                Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
              </p>

              <h3 className="font-bold text-charcoal mb-4">Other Legal Requirements</h3>
              <p className="text-taupe leading-relaxed mb-4 font-body">
                The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
              </p>
              <ul className="list-disc list-inside space-y-2 text-taupe font-body ml-4">
                <li>Comply with a legal obligation</li>
                <li>Protect and defend the rights or property of the Company</li>
                <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                <li>Protect the personal safety of Users of the Service or the public</li>
                <li>Protect against legal liability</li>
              </ul>
            </div>

            {/* Security */}
            <div>
              <h2 className="heading-small mb-6">Security of Your Personal Data</h2>
              <p className="text-taupe leading-relaxed font-body">
                The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
              </p>
            </div>

            {/* Children's Privacy */}
            <div id="children">
              <h2 className="heading-small mb-6">Children's Privacy</h2>
              <p className="text-taupe leading-relaxed mb-4 font-body">
                Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
              </p>
              <p className="text-taupe leading-relaxed font-body">
                If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
              </p>
            </div>

            {/* Links to Other Websites */}
            <div id="links">
              <h2 className="heading-small mb-6">Links to Other Websites</h2>
              <p className="text-taupe leading-relaxed mb-4 font-body">
                Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
              </p>
              <p className="text-taupe leading-relaxed font-body">
                We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
              </p>
            </div>

            {/* Changes to Privacy Policy */}
            <div id="changes">
              <h2 className="heading-small mb-6">Changes to This Privacy Policy</h2>
              <p className="text-taupe leading-relaxed mb-4 font-body">
                We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the 'Last updated' date at the top of this Privacy Policy.
              </p>
              <p className="text-taupe leading-relaxed font-body">
                You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
              </p>
            </div>

            {/* Contact Us */}
            <div id="contact">
              <h2 className="heading-small mb-6">Contact Us</h2>
              <p className="text-taupe leading-relaxed mb-6 font-body">
                If you have any questions about this Privacy Policy, You can contact us:
              </p>
              <div className="bg-ivory p-6 rounded-sm border border-warm-stone">
                <p className="font-body text-charcoal mb-3">
                  <strong>By Email:</strong><br />
                  <a href="mailto:hello@example.com" className="text-gold hover:text-charcoal transition">hello@example.com</a>
                </p>
                <p className="font-body text-charcoal">
                  <strong>By Visiting:</strong><br />
                  <a href="/contact" className="text-gold hover:text-charcoal transition">Pink & Ochre Contact Page</a>
                </p>
              </div>
            </div>

            {/* Last Updated */}
            <div className="mt-16 pt-8 border-t border-warm-stone">
              <p className="text-sm text-taupe">
                <strong>Last Updated:</strong> {lastUpdated}
              </p>
              <p className="text-sm text-taupe mt-2">
                Your privacy is important to us. We are committed to being transparent about how we collect, use, and protect your information.
              </p>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}
